# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d33f50ce08e2e78733f86f373b8e5794b84d94055d173be8ac682fcbe366b61bf8f052e604919115711db38ddd19f66ab59c2ac3a1c393d7e3a093cfed2b2d31

test:
  secret_key_base: 39cd6cb8808065a68e4cc03c6537aebcc326c92e40997fd583b1d0422e05eb90888c6e9ee2391a89639b7a70cc2109634ae30166ecd9c3dded396e2240402180

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
